#!/bin/bash
# smoke tests for resource
set -eu

cleanup() {
    rm -rf ./artifacts
}
trap cleanup EXIT

mkdir -p ./artifacts
echo 'I am the first artifact' > ./artifacts/artifact-full
echo 'I am the second artifact' > ./artifacts/artifact-minimal

export BUILD_JOB_NAME=1
export BUILD_NAME="test"
export BUILD_ID="52026c3b-3fa3-4759-ba29-61a2752e0a06"
export BUILD_PIPELINE_NAME="example-pipeline"
export BUILD_TEAM_NAME="example-team"
export ATC_EXTERNAL_URL="https://ci.example.com"

# run ./out with both inputs. we don't want the report, just logs.
../out < ./request-full.json      1>/dev/null
../out < ./request-minimal.json   1>/dev/null
